name: Build and publish

on:
  push:
    paths-ignore:
    - 'README.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          # TODO: Set up cache
          # See https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
          run_install: |
            args: ["--frozen-lockfile"]
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref_name == "master" }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
